{
 "title": "Sygnal",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "bucket_size",
    "label": "Bucket Size",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(sygnal_notifications_devices_received_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"sygnal\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"sygnal\",instance=~\"$instance\"}",
     "legendFormat": "Open ({{instance}})"
    },
    {
     "expr": "process_max_fds{job=\"sygnal\",instance=~\"$instance\"}",
     "legendFormat": "Max ({{instance}})"
    }
   ]
  },
  { "title": "Inbound Push Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Rate of Inbound Push Requests (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "rate(sygnal_notifications_devices_received_total{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Push by App",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sygnal_per_pushkin_type_total{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (pushkin)",
     "legendFormat": "{{pushkin}}"
    }
   ]
  },
  {
   "title": "Sygnal Successful Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(sygnal_notify_time_bucket{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Sygnal Successful Response Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(sygnal_notify_time_bucket{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(sygnal_notify_time_bucket{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sygnal_notify_time_bucket{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sygnal_notify_time_bucket{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "sum(rate(sygnal_notify_time_sum{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size]))/sum(rate(sygnal_notify_time_count{job=\"sygnal\",instance=~\"$instance\",code=\"200\"}[$bucket_size]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Sygnal Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sygnal_pushgateway_status_codes_total{job=\"sygnal\", instance=~\"$instance\"}[$bucket_size])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Requests in flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sygnal_requests_in_flight{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{resource}}"
    }
   ]
  },
  { "title": "GCM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "GCM requests in queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sygnal_pending_gcm_requests{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GCM Request Queue Time Quantiles",
   "type": "graph",
   "description": "Time spent waiting for a connection to GCM, per request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(sygnal_gcm_queue_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(sygnal_gcm_queue_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sygnal_gcm_queue_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sygnal_gcm_queue_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "sum(rate(sygnal_gcm_queue_time_sum{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) / sum(rate(sygnal_gcm_queue_time_count{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "GCM requests in flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sygnal_active_gcm_requests{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GCM Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sygnal_gcm_status_codes_total{job=\"sygnal\", instance=~\"$instance\"}[$bucket_size])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "GCM Request Time",
   "type": "heatmap",
   "description": "Hisgtogram of time taken for Google to respond to our requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(rate(sygnal_gcm_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GCM Request Send Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(sygnal_gcm_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(sygnal_gcm_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sygnal_gcm_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sygnal_gcm_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "sum(rate(sygnal_gcm_request_time_sum{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) / sum(rate(sygnal_gcm_request_time_count{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size]))",
     "legendFormat": "mean"
    }
   ]
  },
  { "title": "APNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "APNS requests in flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sygnal_active_apns_requests{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "APNS Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sygnal_apns_status_codes_total{job=\"sygnal\", instance=~\"$instance\"}[$bucket_size])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "APNS Request Time",
   "type": "heatmap",
   "description": "Hisgtogram of time taken for Apple to respond to our requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(sygnal_apns_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "APNS Request Send Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(sygnal_apns_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(sygnal_apns_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sygnal_apns_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(sygnal_apns_request_time_bucket{job=\"sygnal\",instance=~\"$instance\"}[$bucket_size])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "rate(sygnal_apns_request_time_sum{instance=~\"$instance\"}[$bucket_size])/rate(sygnal_apns_request_time_count{instance=~\"$instance\"}[$bucket_size])",
     "legendFormat": "mean"
    }
   ]
  }
 ]
}