services:
  sygnal:
    image: localhost/sygnal-with-curl
    build:
      dockerfile: sygnal-with-curl.Dockerfile
    networks:
      no-internet:
        ipv4_address: 172.28.0.2
    container_name: sygnal
    volumes:
      - ./sygnal.yaml:/sygnal.yaml
      - ./service_account.json:/service_account.json:ro
      - ./curl.sh:/curl.sh
      - ./notification-gcm.json:/notification-gcm.json
      - ./notification-ios.json:/notification-ios.json
      - ./mitmproxy:/mitmproxy:ro
    environment:
      SSL_CERT_FILE: /mitmproxy/ca.crt
    ports:
      - 5000:5000

  proxy:
    image: docker.io/mitmproxy/mitmproxy
    command: >-
      mitmdump
      -w /out/mitmdump_out
      --map-local '|https://oauth2.googleapis.com/token|/responses/oauth2_googleapis_token.json'
      --map-local '|https://fcm.googleapis.com/v1/projects/*|/responses/fcm_push.json'
    networks:
      no-internet:
        ipv4_address: 172.28.0.3
      internet:
    container_name: mitmdump
    volumes:
      - ./out:/out:Z
      - ./mitmproxy:/home/mitmproxy/.mitmproxy:z
      - ./responses:/responses:ro
    ports:
      - 8080:8080

networks:
  no-internet:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
  internet:
    driver: bridge
