Name: Changelog
on: [pull_request]

jobs:
  check-newsfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - run: python -m pip install towncrier
      - run: python -m towncrier.check